---
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone=: https://microservice-example-production.up.railway.app/eureka
spring:
  main:
    banner-mode: off
  application:
    name: api-gateway
  cloud:
    gateway:
      #discovery:
        #locator:
          #enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/v1/cars/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/api/v1/bikes/**

management:
  tracing:
    sampling:
      probability: 1.0
...