---
spring:
  devtools:
    add-properties: true
  main:
    banner-mode: off
  application:
    name: user-service
  config:
    import: "optional:configserver:config-server-production-b9e3.up.railway.app"
...