---
server:
  port: 8082

spring:
  application:
    name: config-service
  profiles:
    active: native

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://microservice-example-production.up.railway.app/eureka
...