---
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MarcossIC/Microservice-example.git
          search-path: /config-data/
  main:
    banner-mode: off
  application:
    name: config-service
...
