---
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/MarcossIC/Microservice-example
          search-path: config-data
  main:
    banner-mode: off
  application:
    name: config-service
...
